with-expecter: true
quiet: false
packages:
    go-pvpc/internal:
        config:
            mockname: "{{.InterfaceName}}"
            filename: "{{.InterfaceNameSnake}}.go"
            outpkg: storagemocks
            dir: internal/platform/storage/storagemocks
        interfaces:
            PricesRepository:
            PricesZonesRepository:
