with-expecter: true
quiet: false
case: underscore
packages:
    go-pvpc:
        config:
            outpkg: storagemocks
            output: internal/platform/storage/storagemocks
        interfaces:
            PricesZoneRepository:
