with-expecter: true
quiet: false
packages:
  pvpc-backend/internal/domain:
    config:
      mockname: "{{.InterfaceName}}"
      filename: "{{.InterfaceNameSnake}}.go"
      outpkg: mocks
      dir: internal/mocks
    interfaces:
      PricesRepository:
      ZonesRepository:
