version: "3.1"

services:
  db:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: test_db_user
      POSTGRES_PASSWORD: test_db_pass
      POSTGRES_DB: test_db_name
    ports:
      - 5432:5432
