version: "3.1"

services:
  app:
    build: .
    environment:
      PVPC_DB_USER: test_db_user
      PVPC_DB_PASS: test_db_pass
      PVPC_DB_HOST: db
      PVPC_DB_PORT: 5432
      PVPC_DB_NAME: test_db_name
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: test_db_user
      POSTGRES_PASSWORD: test_db_pass
      POSTGRES_DB: test_db_name
    ports:
      - 5432:5432
